apiVersion: v2
appVersion: 23.9.1
dependencies:
- condition: sourcemaps.enabled
  name: memcached
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 6.5.2
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 17.11.3
- condition: kafka.enabled
  name: kafka
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 22.1.3
- condition: clickhouse.enabled
  name: clickhouse
  repository: https://sentry-kubernetes.github.io/charts
  version: 3.5.0
- condition: zookeeper.enabled
  name: zookeeper
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  version: 9.0.0
- alias: rabbitmq
  condition: rabbitmq.enabled
  name: rabbitmq
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 11.15.3
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.5.1
- condition: nginx.enabled
  name: nginx
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 14.2.2
description: A Helm chart for Kubernetes
maintainers:
- name: sentry-kubernetes
name: sentry
type: application
version: 20.6.1
